// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbc1WN_hWx79xDSIIoFv2BRRzKx5t20V8',
    appId: '1:902816100987:web:f94779c0f181fa8b69a8de',
    messagingSenderId: '902816100987',
    projectId: 'softwie-98760',
    authDomain: 'softwie-98760.firebaseapp.com',
    storageBucket: 'softwie-98760.firebasestorage.app',
    measurementId: 'G-D77WMYNV4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxh9FKp_oIjmol3nm6_3Jc8F-_vHK3Bt8',
    appId: '1:902816100987:android:9342e52f9d26ab4e69a8de',
    messagingSenderId: '902816100987',
    projectId: 'softwie-98760',
    storageBucket: 'softwie-98760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAILuOQYHFCTqYY9x3UpNc_G0eneLUikJA',
    appId: '1:902816100987:ios:b61cdb5564528a2969a8de',
    messagingSenderId: '902816100987',
    projectId: 'softwie-98760',
    storageBucket: 'softwie-98760.firebasestorage.app',
    iosBundleId: 'com.example.softwie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAILuOQYHFCTqYY9x3UpNc_G0eneLUikJA',
    appId: '1:902816100987:ios:b61cdb5564528a2969a8de',
    messagingSenderId: '902816100987',
    projectId: 'softwie-98760',
    storageBucket: 'softwie-98760.firebasestorage.app',
    iosBundleId: 'com.example.softwie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbc1WN_hWx79xDSIIoFv2BRRzKx5t20V8',
    appId: '1:902816100987:web:65fae7bd1679100369a8de',
    messagingSenderId: '902816100987',
    projectId: 'softwie-98760',
    authDomain: 'softwie-98760.firebaseapp.com',
    storageBucket: 'softwie-98760.firebasestorage.app',
    measurementId: 'G-7GNVVEQ0G7',
  );
}
